#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
  set -x
  tsc -p ./tsconfig.build.json
  cat package.json | jq 'del(.main, .types)' >dist/package.json
  set +x
}

build_cp() {
  set -x
  mkdir -p ./dist
  cp -rfv index.js -t ./dist
  cp -fv package.json -t ./dist
  set +x
}

build_pkgroll() {
  set -x
  rm -rf dist
  mkdir dist
  # https://esbuild.github.io/api/#target
  npx pkgroll --target=es2020
  cp -f README.md LICENSE dist
  cat package.json | jq '.main = "./index.cjs"' |
    jq '.module = "./index.mjs"' |
    jq '.types = "./index.d.ts"' |
    jq '.exports.".".import = "./index.mjs"' |
    jq '.exports.".".require = "./index.cjs"' \
      >dist/package.json
  set +x
}

"$@"
